/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "upbdkdcwdolzdcjiyvwe"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwYmRrZGN3ZG9semRjaml5dndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5ODQzNjMsImV4cCI6MjA3ODU2MDM2M30.Zo1M4SUGaI58RiUmNla596lNq-r-IAOI60Lhk4ujlAw"